### ISSUE TITLE
Interpolation error with /dvmvL

### ISSUE THREAD

**Issue by davelab6** [itfoundry/kalam#1]
Interpolation error with `/dvmvL`:

![screen shot 2014-12-04 at 8 57 23 am](https://cloud.githubusercontent.com/assets/261579/5299282/97a9ba28-7b93-11e4-9992-048fcd912c82.png)

**Comment by lianghai** [comment]
As I composing this comment, @lipiraval still refuses to also comment here since she thinks these two issue reports are a single problem — haha, we'll fix this tomorrow morning and push a new build. :D

**Comment by davelab6** [comment]
Thanks!!
